<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php
/** @var $block \Magefan\ProductLabel\Block\LabelCss */
?>

<style>
    /*.mf-label-container {display: block;top:0;right: 0;left: 0;bottom: 0; width: 100%; height: 100%}*/
    .mf-label-container .mf-label {position: absolute; z-index: 9; width: fit-content;}
    .mf-label-container .mf-label.mf-label-position-top-left {top: 0;left: 0;}
</style>



