<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php
/** @var $block \Magefan\ProductLabel\Block\LabelCss */
?>

<style>
    .fotorama .mf-label-position-custom {display: none;}
    .product.media > .mf-label-container {display: none;}
</style>

<script type="text/javascript">
    require(['jquery'], function ($) {
        $('[data-gallery-role=gallery-placeholder]').on('gallery:loaded', function () {
            $(this).parent().find('.mf-label-container').prependTo('<?= $escaper->escapeHtml($block->getConfig()->getProductPageContainerSelector()) ?>')
        });
    });
</script>
