<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<script>
    /* copy of Magefan_ProductLabel::js/label */
    var MagefanPL = {
        processConfigurableProductLabel: function (labelEl, maintProductID, selectedProductId, forProductPage = 0) {
            var self = this;

            if (!window.mfLabelProcessed) {
                window.mfLabelProcessed = {};
            }

            if (!window.mfLabelProcessed[maintProductID]) {
                const url = `${BASE_URL}mfpl/label/get?product_ids=${maintProductID}&get_children=1&product_page=${forProductPage}`;

                MagefanJs.ajax({'url':url, 'type': 'GET',
                    success:  function(response) {
                        response = JSON.parse(response)
                        window.mfLabelProcessed[maintProductID] = response.labels;
                        self.replaceLabel(labelEl, maintProductID, selectedProductId)
                    }
                });
            } else {
                self.replaceLabel(labelEl, maintProductID, selectedProductId)
            }
        },

        replaceLabel: function (labelEl, maintProductID, selectedProductId) {

            let labelHtml =  window.mfLabelProcessed[maintProductID] && window.mfLabelProcessed[maintProductID][selectedProductId]
                ? window.mfLabelProcessed[maintProductID][selectedProductId] : '';

            if (labelHtml) {
                const tempDiv = document.createElement('div');
                tempDiv.innerHTML = labelHtml;
                const newLabel = tempDiv.firstElementChild;

                if (newLabel) {
                    labelEl.replaceWith(newLabel);
                }
            }
        }
    };

    window.addEventListener('configurable-selection-changed', function (e) {
        let labelEl = document.querySelector('.mfpl-product-page'),
            forProductPage = 1;

        if (labelEl) {
            MagefanPL.processConfigurableProductLabel(
                labelEl,
                e.detail.productId,
                e.detail.productIndex,
                forProductPage
            );
        }
    });

    window.addEventListener('listing-configurable-selection-changed', function (e) {
        let labelEl = document.querySelector('input[name="product"][value="'+ e.detail.productId +'"]').closest('form').querySelector('.mf-label-container'),
            forProductPage = 0;

        if (labelEl) {
            MagefanPL.processConfigurableProductLabel(
                labelEl,
                e.detail.productId,
                e.detail.productIndex,
                forProductPage
            );
        }
    });

</script>