<?php
/**
 * Copyright © Magefan (support@magefan.com). All rights reserved.
 * Please visit Magefan.com for license details (https://magefan.com/end-user-license-agreement).
 */
?>
<?php
/**
 * @var $block Magefan\ProductLabel\Block\Adminhtml\System\Config\Form\CheckEnableInfo
 */
?>
<?php if (!$block->isEnabled()) { ?>
<div class="messages">
    <div class="message message-error">
        <div data-ui-id="messages-message-error">
            <?= /*@noEscape*/
            __(
                'Magefan Product Label is disabled, to enable the extension please navigate to
                        <a href="%1" target="_blank">Stores > Configuration > Magefan Extensions > Product Label</a>.',
                $block->getUrl(
                    'adminhtml/system_config/edit',
                    ['section' => 'mfproductlabel']
                )
            );
            ?>
        </div>
    </div>
</div>
<?php } ?>
